default['updatedb']['locate_pkg'] = 'locate'
default['updatedb']['prune_bind_mounts'] = 'yes'
default['updatedb']['prunenames'] = '.git .bzr .hg .svn'
default['updatedb']['prunepaths'] = '/tmp /var/spool /media /home/.ecryptfs .git .svn'
default['updatedb']['prunefs'] = 'NFS nfs nfs4 rpc_pipefs afs binfmt_misc proc smbfs autofs iso9660 ncpfs coda devpts ftpfs devfs mfs shfs sysfs cifs lustre_lite tmpfs usbfs udf fuse.glusterfs fuse.sshfs curlftpfs ecryptfs fusesmb devtmpfs'
